services:
  web:
    build: .
    ports:
      - "5000:5000"
      - "5678:5678"
    volumes:
      - .:/app
    command: ["sh","-c","pip install debugpy && python -m debugpy --listen 0.0.0.0:5001 --wait-for-client -m flask run --host=0.0.0.0 --ports 5000"]